version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
#    allow:
#      - dependency-name: "org.apache.beam:beam-sdks-java-bom"
#      - dependency-name: "com.solacesystems:*"
